#!/bin/sh

GUCEM_SECRET_KEY="abc"
GUCEM_MAIL_HOST="xxx" 
GUCEM_MAIL_PORT=0
GUCEM_MAIL_USER="a@b.c"
GUCEM_MAIL_PASSWORD="xxx"

export GUCEM_SECRET_KEY
export GUCEM_MAIL_HOST
export GUCEM_MAIL_PORT
export GUCEM_MAIL_USER
export GUCEM_MAIL_PASSWORD
